[package]
default-run = "fm"
edition = "2021"
name = "fm"
version = "1.0.0"

[[bin]]
name = "fm"
path = "src/main.rs"

[[bin]]
name = "fm-server"
path = "server/main.rs"

[[bin]]
name = "fm-client"
path = "client/main.rs"

[profile]
dev = { opt-level = 0, debug = true }
release = { opt-level = 3, debug = false }

[dependencies]
anyhow = "1.0.70"
byteorder = "1.4.3"
bytes = "1.4.0"
clap = { version = "4.0.18", default-features = false, features = ["std"] }
crossterm = { version = "0.26", features = ["event-stream"] }
env_logger = "0.10.0"
fs4 = { version = "0.6.4", features = ["tokio-async"] }
futures = "0.3.27"
git2 = "0.16.1"
log = "0.4.20"
prost = "0.11.8"
prost-types = "0.11.8"
serde = { version = "1.0.158", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
toml = "0.7.3"
tui = { git = "file:///home/admin/Storage/Code/69506330/tui", branch = "custom", default-features = true }
walkdir = "2.3.3"

[build-dependencies]
prost-build = "0.5"
